# Synthetics config, which currently only supports the chutes validator but can be extended to support any.
synthetics:
  enabled: true

  # Use LLMs synthetically?
  text:
    enabled: true
    render: true
    dataset:
      name: allenai/WildChat-1M
      options:
        split: train
      field_name: conversation

  # Generate images synthetically?
  image:
    enabled: true
    render: true
    dataset:
      name: Falah/image_generation_prompts_SDXL
      options:
        split: train
      field_name: prompts

  # Text to speech?
  tts:
    enabled: true
    render: true

  # Transcribe?
  transcribe:
    enabled: true
    render: true

  # Embeddings?
  embed:
    enabled: true
    render: true

  # Moderation.
  moderation:
    enabled: true
    render: true

  # API key to use for synthetics - need to register new user(s) first, then generate API key(s)
  api_key: cpk_53a08efc396d4e31990420b1c6b153f5.dff3e6bb3a6b5a2b9c48da3abcd5ca5f.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

# Which validators to audit.
validators:
- name: Chutes
  hotkey: 5Dt7HZ7Zpw4DppPxFM7Ke3Cm7sDAWhsZXmM5ZAmE7dSVJbcQ
  url: https://api.chutes.ai

# Subtensor node to query.
subtensor: wss://entrypoint-finney.opentensor.ai

# Weight setting.
set_weights:
  # Only available/functional if you are a registered validator on subnet 64 with sufficient stake.
  enabled: false
  # This is the ss58Address from the hotkey JSON
  ss58_address: 5GerCEPSx22bmr5Wnm2wj87SSpZiVvhVqFUrGG5795XkUbjr
  # This is the secretSeed value from hotkey JSON
  secret_seed: 0x971c2a6674d0861ade72297d11110ce21c93734210527c8f4c9190c00139ce20
