services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chutes_audit
    volumes:
      - pg_data2:/var/lib/postgresql/data
    restart: always

  auditor:
    build:
      context: .
      no_cache: true
    working_dir: /audit
    command: uv run python audit.py
    volumes:
      - ${PWD}/audit.py:/audit/audit.py
      - ${PWD}/config:/audit/config
      - hfhub:/root/.cache/huggingface
      - ./reports:/reports
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chutes_audit
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - SKIP_MINER_AUDITS=${SKIP_MINER_AUDITS:-true}
      - CALCULATE_MINER_AGREEMENT=${CALCULATE_MINER_AGREEMENT:-false}
    restart: always
    depends_on:
      - postgres

volumes:
  pg_data2:
  hfhub:
